"""Add tutor availability info

Revision ID: da870c1d2a90
Revises: 62e19c67f8c2
Create Date: 2026-03-11 08:21:50.431552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da870c1d2a90'
down_revision = '62e19c67f8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.drop_column('availability_info')

    # ### end Alembic commands ###
